In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [48]:
train_file = 'train_FD003.txt'
index_names = ['unit_nr', 'time_cycles']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names = ['s_{}'.format(i) for i in range(1,22)] 
col_names = index_names + setting_names + sensor_names

# read data
train = pd.read_csv((train_file), sep='\s+', header=None, 
                 names=col_names)

pd.set_option('display.max_columns', None)

train.describe()
#s1 s5 s6 s16 s18 s19

,unit_nr,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21
count,24720.000000,24720.000000,24720.000000,24720.000000,24720.0,2.472000e+04,24720.000000,24720.000000,24720.000000,2.472000e+04,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,24720.000000,2.472000e+04,24720.000000,24720.0,24720.0,24720.000000,24720.000000
mean,48.631877,139.077063,-0.000024,0.000005,100.0,5.186700e+02,642.457858,1588.079175,1404.471212,1.462000e+01,21.595841,555.143808,2388.071555,9064.110809,1.301232,47.415707,523.050873,2388.071643,8144.202916,8.396176,3.000000e-02,392.566545,2388.0,100.0,38.988552,23.393024
std,29.348985,98.846675,0.002194,0.000294,0.0,6.684921e-11,0.523031,6.810418,9.773178,3.602525e-12,0.018116,3.437343,0.158285,19.980294,0.003485,0.300074,3.255314,0.158121,16.504118,0.060512,1.750371e-14,1.761459,0.0,0.0,0.248865,0.149234
min,1.000000,1.000000,-0.008600,-0.000600,100.0,5.186700e+02,640.840000,1564.300000,1377.060000,1.462000e+01,21.450000,549.610000,2386.900000,9017.980000,1.290000,46.690000,517.770000,2386.930000,8099.680000,8.156300,3.000000e-02,388.000000,2388.0,100.0,38.170000,22.872600
25%,23.000000,62.000000,-0.001500,-0.000200,100.0,5.186700e+02,642.080000,1583.280000,1397.187500,1.462000e+01,21.580000,553.110000,2388.000000,9051.920000,1.300000,47.190000,521.150000,2388.010000,8134.510000,8.360600,3.000000e-02,391.000000,2388.0,100.0,38.830000,23.296200
50%,47.000000,124.000000,0.000000,-0.000000,100.0,5.186700e+02,642.400000,1587.520000,1402.910000,1.462000e+01,21.600000,554.050000,2388.070000,9060.010000,1.300000,47.360000,521.980000,2388.070000,8141.200000,8.398300,3.000000e-02,392.000000,2388.0,100.0,38.990000,23.391600
75%,74.000000,191.000000,0.001500,0.000300,100.0,5.186700e+02,642.790000,1592.412500,1410.600000,1.462000e+01,21.610000,556.040000,2388.140000,9070.092500,1.300000,47.600000,523.840000,2388.140000,8149.230000,8.437000,3.000000e-02,394.000000,2388.0,100.0,39.140000,23.483300
max,100.000000,525.000000,0.008600,0.000700,100.0,5.186700e+02,645.110000,1615.390000,1441.160000,1.462000e+01,21.610000,570.490000,2388.600000,9234.350000,1.320000,48.440000,537.400000,2388.610000,8290.550000,8.570500,3.000000e-02,399.000000,2388.0,100.0,39.850000,23.950500

In [34]:
train=train.drop(['s_1', 's_5','s_6','s_10','s_16','s_18','s_19','setting_1','setting_2','setting_3'],axis=1)

In [35]:
grouped_by_unit = train.groupby(by="unit_nr")
max_cycle = grouped_by_unit["time_cycles"].max()
max_cycle.max()

import datetime


dates=[]
for cycle,unit_nr in zip(train['time_cycles'],train['unit_nr']):
    dates.append( (datetime.datetime(2000, 1, 1) + datetime.timedelta(days=cycle)+ datetime.timedelta(seconds=unit_nr)) )

train['Artficial_timestamp']=dates
train.head()
grouped=train.groupby(by="unit_nr")

dfs=[grouped.get_group(x) for x in grouped.groups]
print(len(dfs))

100

In [36]:
%matplotlib qt

# create empty list
dataframes_list = []
 
# append datasets to the list
endes=[]
endswithIndex=[]
for i in range(len(dfs)):
    temp_df = dfs[i]
    dataframes_list.append(temp_df)
    endswithIndex.append((i,len(temp_df.index)))
    endes.append(len(temp_df.index))
print(endswithIndex)
# fixed bin size
bins = np.arange(0, 400, 5) # fixed bin size

plt.xlim([min(endes)-100, max(endes)+100])

plt.hist(endes, bins=bins, alpha=0.5)
plt.show()

[(0, 259), (1, 253), (2, 222), (3, 272), (4, 213), (5, 278), (6, 424), (7, 267), (8, 406), (9, 481), (10, 197), (11, 170), (12, 185), (13, 207), (14, 202), (15, 344), (16, 312), (17, 447), (18, 229), (19, 338), (20, 220), (21, 192), (22, 196), (23, 494), (24, 193), (25, 243), (26, 320), (27, 200), (28, 223), (29, 218), (30, 183), (31, 189), (32, 231), (33, 459), (34, 231), (35, 324), (36, 324), (37, 201), (38, 288), (39, 188), (40, 295), (41, 193), (42, 321), (43, 180), (44, 205), (45, 204), (46, 269), (47, 174), (48, 256), (49, 161), (50, 190), (51, 222), (52, 164), (53, 194), (54, 525), (55, 195), (56, 215), (57, 178), (58, 299), (59, 190), (60, 199), (61, 246), (62, 231), (63, 195), (64, 234), (65, 165), (66, 263), (67, 201), (68, 170), (69, 172), (70, 409), (71, 232), (72, 215), (73, 193), (74, 259), (75, 153), (76, 255), (77, 221), (78, 166), (79, 147), (80, 347), (81, 285), (82, 181), (83, 226), (84, 266), (85, 341), (86, 172), (87, 322), (88, 207), (89, 181), (90, 156), (91, 158), (92, 171), (93, 392), (94, 166), (95, 491), (96, 275), (97, 307), (98, 145), (99, 152)]

In [37]:
endswithIndex=sorted(endswithIndex, key=lambda tup: tup[1])
endes.sort()
print(endswithIndex)

[(98, 145), (79, 147), (99, 152), (75, 153), (90, 156), (91, 158), (49, 161), (52, 164), (65, 165), (78, 166), (94, 166), (11, 170), (68, 170), (92, 171), (69, 172), (86, 172), (47, 174), (57, 178), (43, 180), (82, 181), (89, 181), (30, 183), (12, 185), (39, 188), (31, 189), (50, 190), (59, 190), (21, 192), (24, 193), (41, 193), (73, 193), (53, 194), (55, 195), (63, 195), (22, 196), (10, 197), (60, 199), (27, 200), (37, 201), (67, 201), (14, 202), (45, 204), (44, 205), (13, 207), (88, 207), (4, 213), (56, 215), (72, 215), (29, 218), (20, 220), (77, 221), (2, 222), (51, 222), (28, 223), (83, 226), (18, 229), (32, 231), (34, 231), (62, 231), (71, 232), (64, 234), (25, 243), (61, 246), (1, 253), (76, 255), (48, 256), (0, 259), (74, 259), (66, 263), (84, 266), (7, 267), (46, 269), (3, 272), (96, 275), (5, 278), (81, 285), (38, 288), (40, 295), (58, 299), (97, 307), (16, 312), (26, 320), (42, 321), (87, 322), (35, 324), (36, 324), (19, 338), (85, 341), (15, 344), (80, 347), (93, 392), (8, 406), (70, 409), (6, 424), (17, 447), (33, 459), (9, 481), (95, 491), (23, 494), (54, 525)]

In [38]:
step=5
Buildtuples=[]
Buildtuplesindexes=[]
for i in range(int(len(endes)/step)):
    temptuple=[]
    temptupleindexes=[]
    for j in range(step):
        temptuple.append(endes[i+int(len(endes)/step)*j])
        temptupleindexes.append(i+int(len(endes)/step)*j)
    Buildtuples.append(temptuple)
    Buildtuplesindexes.append(temptupleindexes)
    print(temptuple)
Buildtuples2=[]
Buildtuplesindexes2=[]
for i in range(int(len(Buildtuples)/step)):
    temptuple=[]
    temptupleindexes=[]
    for j in range(step):
        temptuple.append(Buildtuples[i+int(len(Buildtuples)/step)*j])
        temptupleindexes.append(Buildtuplesindexes[i+int(len(Buildtuples)/step)*j])
    Buildtuples2.append(temptuple)
    Buildtuplesindexes2.append(temptupleindexes)
    print(temptuple)
    print(temptupleindexes)

[145, 181, 202, 234, 312]
[147, 183, 204, 243, 320]
[152, 185, 205, 246, 321]
[153, 188, 207, 253, 322]
[156, 189, 207, 255, 324]
[158, 190, 213, 256, 324]
[161, 190, 215, 259, 338]
[164, 192, 215, 259, 341]
[165, 193, 218, 263, 344]
[166, 193, 220, 266, 347]
[166, 193, 221, 267, 392]
[170, 194, 222, 269, 406]
[170, 195, 222, 272, 409]
[171, 195, 223, 275, 424]
[172, 196, 226, 278, 447]
[172, 197, 229, 285, 459]
[174, 199, 231, 288, 481]
[178, 200, 231, 295, 491]
[180, 201, 231, 299, 494]
[181, 201, 232, 307, 525]
[[145, 181, 202, 234, 312], [156, 189, 207, 255, 324], [165, 193, 218, 263, 344], [170, 195, 222, 272, 409], [174, 199, 231, 288, 481]]
[[0, 20, 40, 60, 80], [4, 24, 44, 64, 84], [8, 28, 48, 68, 88], [12, 32, 52, 72, 92], [16, 36, 56, 76, 96]]
[[147, 183, 204, 243, 320], [158, 190, 213, 256, 324], [166, 193, 220, 266, 347], [171, 195, 223, 275, 424], [178, 200, 231, 295, 491]]
[[1, 21, 41, 61, 81], [5, 25, 45, 65, 85], [9, 29, 49, 69, 89], [13, 33, 53, 73, 93], [17, 37, 57, 77, 97]]
[[152, 185, 205, 246, 321], [161, 190, 215, 259, 338], [166, 193, 221, 267, 392], [172, 196, 226, 278, 447], [180, 201, 231, 299, 494]]
[[2, 22, 42, 62, 82], [6, 26, 46, 66, 86], [10, 30, 50, 70, 90], [14, 34, 54, 74, 94], [18, 38, 58, 78, 98]]
[[153, 188, 207, 253, 322], [164, 192, 215, 259, 341], [170, 194, 222, 269, 406], [172, 197, 229, 285, 459], [181, 201, 232, 307, 525]]
[[3, 23, 43, 63, 83], [7, 27, 47, 67, 87], [11, 31, 51, 71, 91], [15, 35, 55, 75, 95], [19, 39, 59, 79, 99]]

In [39]:
Buildtuples3=Buildtuples2
flat_list1 = [item for sublist in Buildtuples3[0] for item in sublist]# for item2 in item]
#print(Buildtuplesindexes2)
flat_listindexes1 = [item for sublist in Buildtuplesindexes2[0] for item in sublist]# for item2 in item]
print(flat_listindexes1)
flat_list1.sort()
#print(flat_list1)
pairlist1=[(0,i) for i in flat_list1]
#print(pairlist1)

[0, 20, 40, 60, 80, 4, 24, 44, 64, 84, 8, 28, 48, 68, 88, 12, 32, 52, 72, 92, 16, 36, 56, 76, 96]

In [40]:
def refporpotion(flat_list1):
    normalrefs=[]
    #print(endes)
    mindist=60
    for item in flat_list1:
        counter=0
        for end in flat_list1:
            if end[0]<=item[1] and end[1]-item[1]>mindist:
                counter+=1
        normalrefs.append(counter)

    badrefs=[]
    for item in flat_list1:
        counter=0
        for end in flat_list1:
            if end[0]<=item[1] and   abs(end[1]-item[1])<=mindist:
                counter+=1
        badrefs.append(counter)

    dif_bad_normal=[]
    for i in range(len(badrefs)):
        if normalrefs[i]==0:
            good_bad_porpotion=0
        else:
            good_bad_porpotion=normalrefs[i]/(normalrefs[i]+badrefs[i])
        dif_bad_normal.append(good_bad_porpotion)
    return dif_bad_normal

In [41]:
normalrefs=[]
flat_list1=pairlist1
#print(endes)
mindist=60
for item in flat_list1:
    counter=0
    for end in flat_list1:
        if end[0]<=item[1] and end[1]-item[1]>mindist:
            counter+=1
    normalrefs.append(counter)
print(normalrefs)

badrefs=[]
for item in flat_list1:
    counter=0
    for end in flat_list1:
        if end[0]<=item[1] and abs(end[1]-item[1])<=mindist:
            counter+=1
    badrefs.append(counter)
print(badrefs)

dif_bad_normal=[]
for i in range(len(badrefs)):
    if normalrefs[i]==0:
        good_bad_porpotion=0
    else:
        good_bad_porpotion=normalrefs[i]/(normalrefs[i]+badrefs[i])
    dif_bad_normal.append(good_bad_porpotion)
print(dif_bad_normal)

[14, 13, 11, 11, 9, 9, 9, 9, 8, 8, 8, 7, 6, 6, 5, 5, 4, 4, 3, 2, 2, 2, 2, 1, 0]
[11, 12, 14, 14, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 16, 16, 13, 10, 10, 9, 7, 5, 4, 1, 1]
[0.56, 0.52, 0.44, 0.44, 0.36, 0.36, 0.36, 0.36, 0.32, 0.32, 0.32, 0.2916666666666667, 0.2608695652173913, 0.2608695652173913, 0.23809523809523808, 0.23809523809523808, 0.23529411764705882, 0.2857142857142857, 0.23076923076923078, 0.18181818181818182, 0.2222222222222222, 0.2857142857142857, 0.3333333333333333, 0.5, 0]

In [42]:
Buildtuples3=Buildtuples2
reffs=[]
reffsindexes=[]

for lllist in Buildtuples3[1:]:
    reffs.extend(lllist)

for lllist in Buildtuplesindexes2[1:]:
    reffsindexes.extend(lllist)


flat_list2 = [item for sublist in reffs for item in sublist]# for item2 in item]
flat_list2.sort()
flat_listindexes2 = [item for sublist in reffsindexes for item in sublist]# for item2 in item]
print(flat_listindexes2)
#print(flat_list2)
pairlist2=[(0,i) for i in flat_list2]
print(pairlist2)

[1, 21, 41, 61, 81, 5, 25, 45, 65, 85, 9, 29, 49, 69, 89, 13, 33, 53, 73, 93, 17, 37, 57, 77, 97, 2, 22, 42, 62, 82, 6, 26, 46, 66, 86, 10, 30, 50, 70, 90, 14, 34, 54, 74, 94, 18, 38, 58, 78, 98, 3, 23, 43, 63, 83, 7, 27, 47, 67, 87, 11, 31, 51, 71, 91, 15, 35, 55, 75, 95, 19, 39, 59, 79, 99]
[(0, 147), (0, 152), (0, 153), (0, 158), (0, 161), (0, 164), (0, 166), (0, 166), (0, 170), (0, 171), (0, 172), (0, 172), (0, 178), (0, 180), (0, 181), (0, 183), (0, 185), (0, 188), (0, 190), (0, 190), (0, 192), (0, 193), (0, 193), (0, 194), (0, 195), (0, 196), (0, 197), (0, 200), (0, 201), (0, 201), (0, 204), (0, 205), (0, 207), (0, 213), (0, 215), (0, 215), (0, 220), (0, 221), (0, 222), (0, 223), (0, 226), (0, 229), (0, 231), (0, 231), (0, 232), (0, 243), (0, 246), (0, 253), (0, 256), (0, 259), (0, 259), (0, 266), (0, 267), (0, 269), (0, 275), (0, 278), (0, 285), (0, 295), (0, 299), (0, 307), (0, 320), (0, 321), (0, 322), (0, 324), (0, 338), (0, 341), (0, 347), (0, 392), (0, 406), (0, 424), (0, 447), (0, 459), (0, 491), (0, 494), (0, 525)]

In [43]:
goodlimit=0.65
while len(pairlist2)>0:
    targetpos=-1
    c=0
    porpotion=refporpotion(pairlist1)
    for item in porpotion:
        if item<goodlimit:
            targetpos=c
            break
        c+=1
    if targetpos==-1:
        break
    targettuple=pairlist1[targetpos]
    goodrefs=normalrefs[targetpos]
    badref=badrefs[targetpos]
    toextend=[]
    used=[]
    isDone=False
    i=0
    while len(pairlist2)>i and isDone==False:
        temp=pairlist2[i]
        shift=targettuple[0]+int(2*targettuple[1]/3)
        temp=(temp[0]+shift,temp[1]+shift)
        if temp[0]<targettuple[1] and temp[1]-targettuple[1]>mindist:
            goodrefs+=1
            toextend.append(temp)
            used.append(i)
        if goodrefs/(goodrefs+badref)>goodlimit:
            isDone=True
        i+=1
    newpairlist1=[]
    newpairlist1.extend(pairlist1)
    newpairlist1.extend(toextend)
    print(used)
    newpairlist2=[]
    for i in range(len(pairlist2)):
        if i not in used:
            newpairlist2.append(pairlist2[i])
    pairlist1=newpairlist1
    pairlist2=newpairlist2

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [44]:
dif_bad_normal=refporpotion(pairlist1)
print(dif_bad_normal)
print(pairlist1)
flat_listindexes1.extend(flat_listindexes2)
PairIndexes=flat_listindexes1
print(PairIndexes)

[0.8735632183908046, 0.88, 0.86, 0.86, 0.84, 0.84, 0.81, 0.81, 0.79, 0.78, 0.76, 0.7575757575757576, 0.7040816326530612, 0.6938775510204082, 0.65625, 0.65625, 0.5652173913043478, 0.5168539325842697, 0.4772727272727273, 0.45348837209302323, 0.3950617283950617, 0.4, 0.3382352941176471, 0.358974358974359, 0.3684210526315789, 0.6702127659574468, 0.6276595744680851, 0.6063829787234043, 0.5652173913043478, 0.5384615384615384, 0.5333333333333333, 0.5222222222222223, 0.5, 0.4772727272727273, 0.4772727272727273, 0.4659090909090909, 0.4659090909090909, 0.45977011494252873, 0.45348837209302323, 0.45348837209302323, 0.45348837209302323, 0.45348837209302323, 0.42168674698795183, 0.3855421686746988, 0.3855421686746988, 0.3855421686746988, 0.3902439024390244, 0.3902439024390244, 0.3950617283950617, 0.3950617283950617, 0.3950617283950617, 0.3950617283950617, 0.4050632911392405, 0.3924050632911392, 0.3924050632911392, 0.38461538461538464, 0.38961038961038963, 0.39473684210526316, 0.38666666666666666, 0.3783783783783784, 0.3783783783783784, 0.36619718309859156, 0.37681159420289856, 0.31746031746031744, 0.31746031746031744, 0.30158730158730157, 0.30158730158730157, 0.3064516129032258, 0.3064516129032258, 0.3064516129032258, 0.3333333333333333, 0.3469387755102041, 0.35555555555555557, 0.36363636363636365, 0.38095238095238093, 0.38095238095238093, 0.35, 0.35, 0.35, 0.358974358974359, 0.3076923076923077, 0.32432432432432434, 0.28125, 0.28125, 0.26666666666666666, 0.3076923076923077, 0.3076923076923077, 0.38095238095238093, 0.38095238095238093, 0.3684210526315789, 0.3684210526315789, 0.35294117647058826, 0.3333333333333333, 0.3333333333333333, 0.375, 0.125, 0.14285714285714285, 0, 0, 0]
[(0, 145), (0, 156), (0, 165), (0, 170), (0, 174), (0, 181), (0, 189), (0, 193), (0, 195), (0, 199), (0, 202), (0, 207), (0, 218), (0, 222), (0, 231), (0, 234), (0, 255), (0, 263), (0, 272), (0, 288), (0, 312), (0, 324), (0, 344), (0, 409), (0, 481), (96, 243), (96, 248), (96, 249), (96, 254), (96, 257), (96, 260), (96, 262), (104, 270), (104, 274), (104, 275), (104, 276), (104, 276), (104, 282), (104, 284), (104, 285), (104, 287), (104, 289), (116, 304), (116, 306), (116, 306), (116, 308), (116, 309), (116, 309), (116, 310), (116, 311), (116, 312), (116, 313), (116, 316), (116, 317), (116, 317), (116, 320), (116, 321), (116, 323), (116, 329), (116, 331), (116, 331), (116, 336), (116, 337), (134, 356), (134, 357), (134, 360), (134, 363), (134, 365), (134, 365), (134, 366), (134, 377), (134, 380), (134, 387), (134, 390), (134, 393), (134, 393), (134, 400), (134, 401), (134, 403), (134, 409), (134, 412), (134, 419), (134, 429), (134, 433), (134, 441), (134, 454), (134, 455), (148, 470), (148, 472), (148, 486), (148, 489), (148, 495), (148, 540), (148, 554), (148, 572), (148, 595), (148, 607), (148, 639), (148, 642), (148, 673)]
[0, 20, 40, 60, 80, 4, 24, 44, 64, 84, 8, 28, 48, 68, 88, 12, 32, 52, 72, 92, 16, 36, 56, 76, 96, 1, 21, 41, 61, 81, 5, 25, 45, 65, 85, 9, 29, 49, 69, 89, 13, 33, 53, 73, 93, 17, 37, 57, 77, 97, 2, 22, 42, 62, 82, 6, 26, 46, 66, 86, 10, 30, 50, 70, 90, 14, 34, 54, 74, 94, 18, 38, 58, 78, 98, 3, 23, 43, 63, 83, 7, 27, 47, 67, 87, 11, 31, 51, 71, 91, 15, 35, 55, 75, 95, 19, 39, 59, 79, 99]

In [45]:
import matplotlib.pyplot as plt


yax=0
indexwithshift=[]
good=[]
for tuplee in pairlist1:
    indexwithshift.append((endswithIndex[PairIndexes[yax]][0],tuplee[0]))
    if dif_bad_normal[yax]>0.65:
        good.append(endswithIndex[PairIndexes[yax]][0])
        yax+=1
        plt.plot((tuplee[0], tuplee[1]), (yax, yax), 'b-')
    else:
        yax+=1
        plt.plot((tuplee[0], tuplee[1]), (yax, yax), 'r-')
print(good)

[98, 89, 14, 64, 16, 90, 31, 88, 76, 35, 65, 24, 29, 66, 15, 68, 79]

In [46]:
for ind in indexwithshift:
    dates=[]
    for cycle,unit_nr in zip(dataframes_list[ind[0]]['time_cycles'],dataframes_list[ind[0]]['unit_nr']):
        dates.append( (datetime.datetime(2000, 1, 1) + datetime.timedelta(days=cycle+ind[1])+ datetime.timedelta(seconds=unit_nr)) )
    dataframes_list[ind[0]]['Artficial_timestamp']=dates
    dataframes_list[ind[0]]=dataframes_list[ind[0]].set_index('Artficial_timestamp')
    dataframes_list[ind[0]]=dataframes_list[ind[0]].drop(['unit_nr', 'time_cycles'], axis=1)
    dataframes_list[ind[0]].to_csv('f0003/f03_'+str(ind[0])+'.csv')

<ipython-input-46-6c9783002998>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframes_list[ind[0]]['Artficial_timestamp']=dates

IndexError: list index out of range

In [47]:
dataframes_list[0].head()

,s_2,s_3,s_4,s_7,s_8,s_9,s_10,s_11,s_12,s_13,s_14,s_15,s_17,s_20,s_21
Artficial_timestamp,,,,,,,,,,,,,,,
2000-04-27 00:00:01,642.36,1583.23,1396.84,553.97,2387.96,9062.17,1.3,47.30,522.31,2388.01,8145.32,8.4246,391,39.11,23.3537
2000-04-28 00:00:01,642.50,1584.69,1396.89,554.55,2388.00,9061.78,1.3,47.23,522.42,2388.03,8152.85,8.4403,392,38.99,23.4491
2000-04-29 00:00:01,642.18,1582.35,1405.61,554.43,2388.03,9070.23,1.3,47.22,522.03,2388.00,8150.17,8.3901,391,38.85,23.3669
2000-04-30 00:00:01,642.92,1585.61,1392.27,555.21,2388.00,9064.57,1.3,47.24,522.49,2388.08,8146.56,8.3878,392,38.96,23.2951
2000-05-01 00:00:01,641.68,1588.63,1397.65,554.74,2388.04,9076.14,1.3,47.15,522.58,2388.03,8147.80,8.3869,392,39.14,23.4583